### ISSUE TITLE
VSCode extension cannot fetch json file

### ISSUE THREAD

**Issue by EvanHsieh0415** [TeamDman/tell-me-my-items#1]
![img](https://user-images.githubusercontent.com/74277414/209512638-afffa5dc-7380-4607-9af4-892d508327b3.png)
![img](https://user-images.githubusercontent.com/74277414/209512670-91410ae8-9db3-45c2-8d18-fa128f18e880.png)
![img](https://user-images.githubusercontent.com/74277414/209512709-46ef2fa0-d895-4176-aa19-e408f495424d.png)
As shown in the picture above.
How to solve it?

**Comment by TeamDman** [comment]
Hadn't tested that, published v0.0.3 which should fix the problem

Fixed in 7a1e8a614619687f8ef39b5a55255e4b34384e23

**Comment by EvanHsieh0415** [comment]
![image](https://user-images.githubusercontent.com/74277414/209587807-9c8e0251-2dfe-4135-acbf-9f8318d2972c.png)
Still not work

**Comment by EvanHsieh0415** [comment]
![image](https://user-images.githubusercontent.com/74277414/209589369-dfb43ab4-780d-46bd-93c8-3e3fc7387adf.png)
My bad, the path was typed wrong
But he will not appear to suggest
![image](https://user-images.githubusercontent.com/74277414/209589391-4359fd71-46da-4e74-9139-813b40712b90.png)
I tried to reload the window and restart VScode, but to no avail.

**Comment by TeamDman** [comment]
Does using the "tmmi: reload items from json" palette command or whatever its called help? Might be a problem with the auto start
